import React from "react";
import Head from 'next/head'
import styles from '../../styles/Home.module.css'


export default class Layout extends React.Component {
    render() {
        const { title, description, children } = this.props
        return (
            <div>
                <Head>
                    <title>{title ? title : 'Digital company'} / Next ADV</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="https://www.nextadv.it/wp-content/uploads/2020/06/cropped-favicon-next-blu-32x32.png" sizes="32x32" />
                </Head>
                {children}
                <footer className={styles.footer}>
                    
                </footer>
            </div>
        );
    }
}