import React from "react";
import Head from 'next/head'


export default class Layout extends React.Component {
    render() {
        const { title, description, children } = this.props
        return (
            <div>
                <Head>
                    <title>{title} / Next ADV</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                {children}
            </div>
        );
    }
}